# Generated by Django 5.1.4 on 2024-12-26 18:53

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = [
        ("pyjams", "0001_initial"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="user",
            name="spotify_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
