# Generated by Django 5.1.4 on 2025-01-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pyjams", "0005_alter_featuredplaylist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredplaylist",
            name="featured_type",
            field=models.CharField(
                choices=[("site", "Site Featured"), ("community", "Community Featured")],
                default="community",
                max_length=20,
            ),
        ),
    ]
