name: Django CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: requirements.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Upload virtualenv
      uses: actions/upload-artifact@v3
      with:
        name: venv
        path: |
          .venv
          ~/.cache/pip

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: ['lint', 'pytest', 'django']
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Download virtualenv
      uses: actions/download-artifact@v3
      with:
        name: venv
        path: |
          .venv
          ~/.cache/pip
    
    - name: Run Tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pip install -r requirements.txt
        case ${{ matrix.test-type }} in
          lint)
            invoke lint
            ;;
          pytest)
            invoke test
            ;;
          django)
            python manage.py test
            ;;
        esac
